export { default as IndexRoute } from './IndexRoute'
export { default as AboutRoute } from './AboutRoute'
export { default as ContactRoute } from './ContactRoute'
export { default as ShowRoute } from './ShowRoute'
export { default as TagRoute } from './TagRoute'
